### ISSUE TITLE
Mistake of Fill-in flatten style

### ISSUE THREAD

**Issue by cboonnag** [Sati-Co-Ltd/fill-in-input#4]
In "Blood Urea Nitrogen and Creatine" section of lab.md, Fill-in flatten style of subitem CrCl is "lab:bloodNitrogen:eGFR".  
Is it should be "lab:bloodNitrogen:CrCl" ?

Regards,
cboonnag

**Comment by pahntanapat** [comment]
Fixed copy and paste error
